# Generated by Django 4.2.5 on 2023-09-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.ImageField(upload_to='cars/'),
        ),
    ]
