# Generated by Django 4.2.5 on 2023-09-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
    ]
