# Generated by Django 4.2.5 on 2023-09-10 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='name',
            new_name='pic',
        ),
    ]
